-- ============================================================
-- AI4Groundwater Project Member Directory
-- ============================================================

create table if not exists public.project_member_directory (
    id bigint generated by default as identity primary key,
    project_id bigint not null
        references public.projects(id)
        on delete cascade,
    member_id text not null,
    full_name text not null,
    email text not null,
    project_role text not null default 'team'
        check (project_role in ('PI', 'team')),
    created_at timestamptz not null default now(),

    unique (project_id, member_id)
);

-- ============================================================
-- Project 01
-- ============================================================

insert into public.project_member_directory
    (project_id, member_id, full_name, email, project_role)
select
    pr.id,
    members.member_id,
    members.full_name,
    members.email,
    members.project_role
from public.projects pr
cross join (
    values
        ('P1',  'Demiso Daba (M.Sc) - (PI)', 'demisod390@gmail.com', 'PI'),
        ('P1*', 'Mikiyas Ali',               'mikiasali333@gmail.com', 'team'),
        ('P2',  'Zelalem Anley (M.Sc)',      'zelalemanley3@gmail.com', 'team'),
        ('P3',  'Mullusew Bezabih (M.Sc)',   'bmullusew@gmail.com', 'team'),
        ('P4',  'Sintayehu Yadete (Ph.D.)',  'sintayadete5@gmail.com', 'team'),
        ('P5',  'Meron Mohammed (M.Sc)',     'meronamin23@gmail.com', 'team'),
        ('P6',  'Getachew Enssa (M.Sc)',     'getachew.enssa12@gmail.com', 'team'),
        ('P7',  'Sufiyan Abdurhman (M.Sc)',   'sufi.abdi@gmail.com', 'team'),
        ('P8',  'Aschalewu Cherie (Ph.D.)',  'aschalewc@gmail.com', 'team'),
        ('P9',  'Tafese Fitensa (M.Sc)',     'tatiyihun@gmail.com', 'team'),
        ('P10', 'Kinfe Bereda (M.Sc)',       'kinfem110@gmail.com', 'team'),
        ('P11', 'Babur Tesfaye (M.Sc)',      'baburtesfaye@gmail.com', 'team')
) as members(member_id, full_name, email, project_role)
where pr.project_code = '01'
on conflict (project_id, member_id)
do update set
    full_name = excluded.full_name,
    email = excluded.email,
    project_role = excluded.project_role;

-- ============================================================
-- Project 02
-- ============================================================

insert into public.project_member_directory
    (project_id, member_id, full_name, email, project_role)
select
    pr.id,
    'P3',
    'Mullusew Bezabih (M.Sc)',
    'bmullusew@gmail.com',
    'PI'
from public.projects pr
where pr.project_code = '02'
on conflict (project_id, member_id)
do update set
    full_name = excluded.full_name,
    email = excluded.email,
    project_role = excluded.project_role;

-- ============================================================
-- Security
-- ============================================================

alter table public.project_member_directory enable row level security;

create policy "project_member_directory_read_public"
on public.project_member_directory
for select
to anon
using (true);

create policy "project_member_directory_read"
on public.project_member_directory
for select
to authenticated
using (true);

create index if not exists
project_member_directory_project_id_idx
on public.project_member_directory(project_id);