-- ============================================================
-- AI4Groundwater
-- FINAL TASK SYSTEM FIX
-- ============================================================

-- ============================================================
-- 1. MAKE SURE TASKS TABLE EXISTS
-- ============================================================

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    member_id text not null,
    task text not null,
    start_date date not null,
    end_date date not null,
    task_status text not null default 'Pending',
    payment_status text not null default 'Pending',
    submitted_at timestamptz,
    created_at timestamptz not null default now()
);

-- ============================================================
-- 2. MAKE SURE REQUIRED COLUMNS EXIST
-- ============================================================

alter table public.tasks
add column if not exists member_id text;

alter table public.tasks
add column if not exists task text;

alter table public.tasks
add column if not exists start_date date;

alter table public.tasks
add column if not exists end_date date;

alter table public.tasks
add column if not exists task_status text;

alter table public.tasks
add column if not exists payment_status text;

alter table public.tasks
add column if not exists submitted_at timestamptz;

alter table public.tasks
add column if not exists created_at timestamptz default now();

-- ============================================================
-- 3. FIX DEFAULT VALUES
-- ============================================================

alter table public.tasks
alter column task_status set default 'Pending';

alter table public.tasks
alter column payment_status set default 'Pending';

alter table public.tasks
alter column created_at set default now();

-- ============================================================
-- 4. REMOVE OLD STATUS CONSTRAINT
-- ============================================================

alter table public.tasks
drop constraint if exists tasks_task_status_check;

-- ============================================================
-- 5. ADD FINAL STATUS CONSTRAINT
-- ============================================================

alter table public.tasks
add constraint tasks_task_status_check
check (
    task_status in (
        'Pending',
        'In Progress',
        'Pending Review',
        'Completed',
        'Reassigned'
    )
);

-- ============================================================
-- 6. PAYMENT STATUS CONSTRAINT
-- ============================================================

alter table public.tasks
drop constraint if exists tasks_payment_status_check;

alter table public.tasks
add constraint tasks_payment_status_check
check (
    payment_status in (
        'Pending',
        'Paid'
    )
);

-- ============================================================
-- 7. ENABLE RLS
-- ============================================================

alter table public.tasks enable row level security;

alter table public.profiles enable row level security;

-- ============================================================
-- 8. REMOVE OLD TASK POLICIES
-- ============================================================

drop policy if exists "tasks_read" on public.tasks;
drop policy if exists "tasks_insert" on public.tasks;
drop policy if exists "tasks_update" on public.tasks;

drop policy if exists "Admins can view all tasks" on public.tasks;
drop policy if exists "Admins can insert tasks" on public.tasks;
drop policy if exists "Admins can update tasks" on public.tasks;
drop policy if exists "Members can view own tasks" on public.tasks;
drop policy if exists "Members can submit own tasks" on public.tasks;

-- ============================================================
-- 9. TASK SELECT
--
-- Admin:
--     Can see every task.
--
-- Team member:
--     Can see only their own tasks.
-- ============================================================

create policy "tasks_select_policy"
on public.tasks
for select
to authenticated
using (
    exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
        and p.role = 'admin'
    )
    or
    member_id = (
        select p.member_id
        from public.profiles p
        where p.id = auth.uid()
    )
);

-- ============================================================
-- 10. ADMIN INSERT
--
-- Only an authenticated admin can assign a task.
-- ============================================================

create policy "tasks_admin_insert_policy"
on public.tasks
for insert
to authenticated
with check (
    exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
        and p.role = 'admin'
    )
);

-- ============================================================
-- 11. ADMIN UPDATE
--
-- Admin can change:
--     member
--     task status
--     payment status
-- ============================================================

create policy "tasks_admin_update_policy"
on public.tasks
for update
to authenticated
using (
    exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
        and p.role = 'admin'
    )
)
with check (
    exists (
        select 1
        from public.profiles p
        where p.id = auth.uid()
        and p.role = 'admin'
    )
);

-- ============================================================
-- 12. TEAM MEMBER UPDATE
--
-- Team members can update only their own task.
--
-- The application uses this to submit a task for review.
-- ============================================================

create policy "tasks_member_update_policy"
on public.tasks
for update
to authenticated
using (
    member_id = (
        select p.member_id
        from public.profiles p
        where p.id = auth.uid()
    )
)
with check (
    member_id = (
        select p.member_id
        from public.profiles p
        where p.id = auth.uid()
    )
);

-- ============================================================
-- 13. PROFILE READ POLICY
-- ============================================================

drop policy if exists "profiles_read" on public.profiles;

create policy "profiles_select_policy"
on public.profiles
for select
to authenticated
using (true);

-- ============================================================
-- 14. DATABASE PRIVILEGES
-- ============================================================

grant select on public.tasks to authenticated;
grant insert on public.tasks to authenticated;
grant update on public.tasks to authenticated;

grant select on public.profiles to authenticated;

-- ============================================================
-- 15. ID INDEX
-- ============================================================

create index if not exists tasks_member_id_idx
on public.tasks(member_id);

create index if not exists tasks_created_at_idx
on public.tasks(created_at desc);