-- ============================================================
-- AI4Groundwater Projects
-- ============================================================

create table if not exists public.projects (
    id bigint generated by default as identity primary key,
    project_code text unique not null,
    project_name text not null,
    reference text unique not null,
    pi_name text not null,
    created_at timestamptz not null default now()
);

-- ============================================================
-- PROJECTS
-- ============================================================

insert into public.projects
    (project_code, project_name, reference, pi_name)
values
    (
        '01',
        'AI4Groundwater',
        'Res/AWTI/078/26',
        'Demiso Daba'
    ),
    (
        '02',
        'AI4Groundwater',
        'Res/AWTI/079/26',
        'Mullusew Bezabih'
    )
on conflict (project_code) do update set
    project_name = excluded.project_name,
    reference = excluded.reference,
    pi_name = excluded.pi_name;

-- ============================================================
-- SECURITY
-- ============================================================

alter table public.projects enable row level security;

create policy "projects_read"
on public.projects
for select
to authenticated
using (true);