-- ============================================================
-- AI4Groundwater Database
-- ============================================================

create table if not exists public.profiles (
    id uuid primary key references auth.users(id) on delete cascade,
    member_id text unique not null,
    full_name text not null,
    email text unique not null,
    role text not null default 'team'
        check (role in ('admin', 'team')),
    created_at timestamptz not null default now()
);

create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    member_id text not null,
    task text not null,
    start_date date not null,
    end_date date not null,
    task_status text not null default 'Pending'
        check (task_status in ('Pending', 'In Progress', 'Submitted', 'Completed', 'Reassigned')),
    payment_status text not null default 'Pending'
        check (payment_status in ('Pending', 'Paid')),
    submitted_at timestamptz,
    created_at timestamptz not null default now()
);

-- Add member_id if an older profiles table already exists
alter table public.profiles
add column if not exists member_id text;

-- Add other missing columns if an older table exists
alter table public.profiles
add column if not exists full_name text;

alter table public.profiles
add column if not exists email text;

alter table public.profiles
add column if not exists role text default 'team';

-- Make sure tasks has the required columns
alter table public.tasks
add column if not exists member_id text;

alter table public.tasks
add column if not exists task text;

alter table public.tasks
add column if not exists start_date date;

alter table public.tasks
add column if not exists end_date date;

alter table public.tasks
add column if not exists task_status text default 'Pending';

alter table public.tasks
add column if not exists payment_status text default 'Pending';

alter table public.tasks
add column if not exists submitted_at timestamptz;

-- ============================================================
-- Team members
-- ============================================================

insert into public.profiles
    (id, member_id, full_name, email, role)
values
    (
        gen_random_uuid(),
        'P1',
        'Demiso Daba (M.Sc) - (PI)',
        'demisod390@gmail.com',
        'admin'
    ),
    (
        gen_random_uuid(),
        'P1*',
        'Mikiyas Ali',
        'mikiasali333@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P2',
        'Zelalem Anley (M.Sc)',
        'zelalemanley3@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P3',
        'Mullusew Bezabih (M.Sc)',
        'bmullusew@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P4',
        'Sintayehu Yadete (Ph.D.)',
        'sintayadete5@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P5',
        'Meron Mohammed (M.Sc)',
        'meronamin23@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P6',
        'Getachew Enssa (M.Sc)',
        'getachew.enssa12@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P7',
        'Sufiyan Abdurhman (M.Sc)',
        'sufi.abdi@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P8',
        'Aschalewu Cherie (Ph.D.)',
        'aschalewc@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P9',
        'Tafese Fitensa (M.Sc)',
        'tatiyihun@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P10',
        'Kinfe Bereda (M.Sc)',
        'kinfem110@gmail.com',
        'team'
    ),
    (
        gen_random_uuid(),
        'P11',
        'Babur Tesfaye (M.Sc)',
        'baburtesfaye@gmail.com',
        'team'
    )
on conflict (member_id) do update set
    full_name = excluded.full_name,
    email = excluded.email,
    role = excluded.role;

-- ============================================================
-- Security
-- ============================================================

alter table public.profiles enable row level security;
alter table public.tasks enable row level security;

create policy "profiles_read"
on public.profiles
for select
to authenticated
using (true);

create policy "tasks_read"
on public.tasks
for select
to authenticated
using (true);

create policy "tasks_insert"
on public.tasks
for insert
to authenticated
with check (true);

create policy "tasks_update"
on public.tasks
for update
to authenticated
using (true)
with check (true);