-- Fix existing profiles table
alter table public.profiles
add column if not exists member_id text;

alter table public.profiles
add column if not exists full_name text;

alter table public.profiles
add column if not exists email text;

alter table public.profiles
add column if not exists role text default 'team';

-- Make sure tasks table exists
create table if not exists public.tasks (
    id bigint generated by default as identity primary key,
    member_id text not null,
    task text not null,
    start_date date not null,
    end_date date not null,
    task_status text not null default 'Pending',
    payment_status text not null default 'Pending',
    submitted_at timestamptz,
    created_at timestamptz not null default now()
);

alter table public.tasks
add column if not exists member_id text;

alter table public.tasks
add column if not exists task text;

alter table public.tasks
add column if not exists start_date date;

alter table public.tasks
add column if not exists end_date date;

alter table public.tasks
add column if not exists task_status text default 'Pending';

alter table public.tasks
add column if not exists payment_status text default 'Pending';

alter table public.tasks
add column if not exists submitted_at timestamptz;